version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ingest1:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_1_PROD}
      - S3_BUCKET=${S3_BUCKET_PROD}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest1
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  ingest2:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_2_PROD}
      - S3_BUCKET=${S3_BUCKET_PROD}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest2
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  ingest3:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_3_PROD}
      - S3_BUCKET=${S3_BUCKET_PROD}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest3
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  ingest4:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_4_PROD}
      - S3_BUCKET=${S3_BUCKET_PROD}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest4
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  ingest5:
    build: .
    environment:
      - DYNAMODB_TABLE=${DYNAMODB_TABLE_5_PROD}
      - S3_BUCKET=${S3_BUCKET_PROD}
      - FILE_FORMAT=${FILE_FORMAT}
      - CONTAINER_NAME=ingest5
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  etl:
    build: .
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - CONTAINER_NAME=etl
    depends_on:
      - mysql
    volumes:
      - logs:/logs
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
    command: ["python", "etl_service.py"]

volumes:
  mysql_data:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/logs